name             'ccsf'
maintainer       'James Larson'
maintainer_email 'jlarson@tomorrowpartners.com'
license          'All rights reserved'
description      'Installs/Configures ccsf'
long_description 'Installs/Configures ccsf'
version          '0.1.0'

depends 'git'
depends 'postfix'
depends 'drupal'
depends 'mysql'
depends 'database'
depends 'solr'
